
# RAUC updates configuration file

[keyring]
path=/usr/lib/rauc/ca.cert.pem

[system]
compatible=gwcv5
bootloader=uboot
bundle-formats=-plain

[slot.rootfs.0]
device=/dev/ubi0_0
type=ubifs
bootname=rootfs.0
extra-mkfs-opts=-m 4096 -e 253952 -c 1944 -x lzo

[slot.rootfs.1]
device=/dev/ubi0_1
type=ubifs
bootname=rootfs.1
extra-mkfs-opts=-m 4096 -e 253952 -c 1944 -x lzo
